/* generated by scripts/build-client.mjs — do not edit */
window.__ModuleLoader__.load({
  id: "@amorligno/dsh-git-gui",
  factory: function (require) {
    var __modules = {
"./api.js": function (module, exports, require) {
/**
 * Browser → Host RPC wrapper for the `git/*` endpoints (Typert SRC mode).
 *
 * The host plugin binds the `git` namespace; the API gateway accepts plain
 * `{args}` payloads on the shared `/api` channel, so no generated Typert
 * artifacts are required on either side.
 */

class GitApiError extends Error {
  constructor(code, message, detail) {
    super(message)
    this.name = 'GitApiError'
    this.code = code
    this.detail = detail
  }
}

function makeGitApi(connection) {
  async function call(method, args, signal) {
    const result = await connection.rpc.call('/api', `git/${method}`, { args }, signal)
    if (!result.ok) {
      throw new GitApiError(result.error?.code ?? 'internal', result.error?.message ?? `git/${method} 调用失败`)
    }
    const value = result.value
    if (value && typeof value === 'object' && value.ok === false) {
      throw new GitApiError(value.code ?? 'GIT', value.message ?? 'Git 操作失败', value.detail)
    }
    return value
  }

  return {
    call,
    async check(cwd, signal) { return call('check', { cwd }, signal) },
    async status(cwd, signal) { return call('status', { cwd }, signal) },
    async diff(cwd, path, staged, base, untracked, signal) {
      return call('diff', { cwd, path, staged: staged === true, base: base ?? null, untracked: untracked === true }, signal)
    },
    async stage(cwd, paths, signal) { return call('stage', { cwd, paths }, signal) },
    async unstage(cwd, paths, signal) { return call('unstage', { cwd, paths }, signal) },
    async discard(cwd, paths, untracked, signal) { return call('discard', { cwd, paths, untracked: untracked === true }, signal) },
    async commit(cwd, message, signal) { return call('commit', { cwd, message }, signal) },
    async generateCommitMessage(cwd, signal) { return call('generateCommitMessage', { cwd }, signal) },
    async log(cwd, limit, path, signal) { return call('log', { cwd, limit, path: path ?? null }, signal) },
    async branches(cwd, signal) { return call('branches', { cwd }, signal) },
    async switchBranch(cwd, name, create, signal) { return call('switchBranch', { cwd, name, create: create === true }, signal) },
    async merge(cwd, ref, signal) { return call('merge', { cwd, ref }, signal) },
    async pull(cwd, mode, signal) { return call('pull', { cwd, mode }, signal) },
    async push(cwd, signal) { return call('push', { cwd }, signal) },
    async fetch(cwd, signal) { return call('fetch', { cwd }, signal) },
    async remoteList(cwd, signal) { return call('remoteList', { cwd }, signal) },
    async remoteAdd(cwd, name, url, signal) { return call('remoteAdd', { cwd, name, url }, signal) },
    async stash(cwd, op, message, stashId, signal) {
      return call('stash', { cwd, op, message: message ?? null, stashId: stashId ?? null }, signal)
    },
    async revert(cwd, commit, signal) { return call('revert', { cwd, commit }, signal) },
    async reset(cwd, mode, target, signal) { return call('reset', { cwd, mode, target: target ?? 'HEAD' }, signal) },
    async init(cwd, signal) { return call('init', { cwd }, signal) },
    async activity(cwd, limit, signal) { return call('activity', { cwd, limit }, signal) },
    async tree(cwd, signal) { return call('tree', { cwd }, signal) },
    async cat(cwd, path, signal) { return call('cat', { cwd, path }, signal) },
    async identity(cwd, signal) { return call('identity', { cwd }, signal) },
  }
}

module.exports = { makeGitApi, GitApiError }

},
"./control.js": function (module, exports, require) {
/**
 * Panel controller: workspace/session sync, polling, and operation runner.
 * Shared by the sidebar entry button and the overlay panel.
 */
const { setState, getState, resetWorkspace } = require('./store')
const { t } = require('./i18n')

let api = null
let pollTimer = null
let tabLoaders = {}   // tab -> loader fn
let lastBadgeAt = 0
let lastStatusAt = 0

const OPEN_POLL_MS = 2000
const BADGE_POLL_MS = 5000

function startController(gitApi) {
  api = gitApi
  if (pollTimer !== null) return
  pollTimer = setInterval(() => {
    try {
      tick()
    } catch { /* poller must never throw */ }
  }, 1000)
  if (pollTimer.unref) pollTimer.unref()
}

function getApi() {
  return api
}

/**
 * Apply a sessions snapshot (already selected via the useSessions hook in a
 * component) to the store: session id, workspace cwd, and running flag.
 * Called from effects only (never during render).
 */
function applySession(sessions) {
  const currentId = sessions.current
  const summary = currentId !== undefined ? sessions.byId[currentId] : undefined
  const cwd = typeof summary?.cwd === 'string' && summary.cwd !== '' ? summary.cwd : null
  const running = summary?.running === true
  const s = getState()
  if (s.sessionRunning !== running) setState({ sessionRunning: running })
  if (s.sessionId !== currentId || (cwd !== null && s.cwd !== cwd)) {
    if (cwd !== null && s.cwd !== cwd) {
      resetWorkspace(cwd, currentId ?? null)
      refreshCheck()
      refreshStatus()
      refreshRemotes()
      refreshTabData()
    } else if (cwd === null && s.cwd !== null) {
      resetWorkspace(null, currentId ?? null)
    } else if (currentId !== undefined && s.sessionId !== currentId) {
      setState({ sessionId: currentId })
    }
  }
}

/** Load the configured remotes for the current workspace. */
async function refreshRemotes() {
  const s = getState()
  if (!api || s.cwd === null) return
  try {
    const result = await api.remoteList(s.cwd)
    setState({ remotes: result.remotes ?? [] })
  } catch {
    setState({ remotes: [] })
  }
}

function tick() {
  const s = getState()
  if (s.cwd === null || s.check?.repo !== true) return
  if (s.busy) return
  const now = Date.now()
  if (s.open) {
    // status refresh while the panel is open: at most every 2s
    if (now - lastStatusAt < OPEN_POLL_MS) return
    lastStatusAt = now
    refreshStatus()
  } else if (now - lastBadgeAt >= BADGE_POLL_MS) {
    lastBadgeAt = now
    refreshStatus()
  }
}

async function refreshCheck() {
  const s = getState()
  if (!api || s.cwd === null) return
  try {
    const result = await api.check(s.cwd)
    setState({ check: result })
    if (result.repo) refreshStatus()
  } catch (error) {
    setState({ check: { repo: false, gitVersion: '', error: error.message } })
  }
}

async function refreshStatus() {
  const s = getState()
  if (!api || s.cwd === null || s.check?.repo !== true) return
  if (s.busy) return
  try {
    const result = await api.status(s.cwd)
    setState({ status: result, statusError: null })
  } catch (error) {
    setState({ statusError: String(error?.message ?? error) })
  }
}

async function refreshDiff() {
  const s = getState()
  const selected = s.selected
  if (!api || s.cwd === null || selected === null) return
  const key = { ...selected }
  setState({ diff: { ...key, loading: true, error: null, data: null } })
  try {
    const result = selected.cat === true
      ? await api.cat(s.cwd, selected.path)
      : await api.diff(s.cwd, selected.path, selected.staged, null, selected.untracked)
    const current = getState()
    const cur = current.selected
    if (cur === null || cur.path !== selected.path || cur.staged !== selected.staged
      || cur.untracked !== selected.untracked || cur.cat !== selected.cat) return
    setState({ diff: { ...key, loading: false, error: null, data: result } })
  } catch (error) {
    const current = getState()
    const cur = current.selected
    if (cur === null || cur.path !== selected.path) return
    setState({ diff: { ...key, loading: false, error: String(error?.message ?? error), data: null } })
  }
}

function registerTabLoader(tab, loader) {
  tabLoaders[tab] = loader
}

async function refreshTabData() {
  const s = getState()
  const loader = tabLoaders[s.tab]
  if (loader && s.cwd !== null && s.check?.repo === true) {
    try {
      await loader(s.cwd)
    } catch (error) {
      setState({ toast: { kind: 'error', text: String(error?.message ?? error) } })
    }
  }
}

/** Run one user operation: busy state, error toast, refresh afterwards. */
async function run(label, fn, refresh = true) {
  const s = getState()
  if (s.busy) {
    setState({ toast: { kind: 'warn', text: t('toast.busy') } })
    return false
  }
  setState({ busy: true, busyLabel: label })
  try {
    const result = await fn()
    if (result && result.output !== undefined && result.output !== '') {
      setState({ output: { title: label, text: result.output } })
    }
    if (refresh) {
      await Promise.allSettled([refreshStatus(), refreshDiff(), refreshTabData()])
    }
    return true
  } catch (error) {
    setState({
      toast: { kind: 'error', text: String(error?.message ?? error) },
      output: { title: label, text: String(error?.detail ?? error?.message ?? error) },
    })
    if (refresh) await refreshStatus().catch(() => {})
    return false
  } finally {
    setState({ busy: false, busyLabel: '' })
  }
}

/** Ask a confirmation, then run the operation when confirmed. */
function confirmThen({ body, danger, action }) {
  setState({ confirm: { body, danger, action } })
}

/** Settle the open confirm dialog: run the stored action when ok=true. */
function settleConfirm(ok) {
  const s = getState()
  const confirm = s.confirm
  setState({ confirm: null })
  if (ok && confirm) {
    const action = confirm.action
    setTimeout(() => { action() }, 0)
  }
}

module.exports = {
  startController,
  getApi,
  applySession,
  refreshCheck,
  refreshStatus,
  refreshDiff,
  refreshRemotes,
  refreshTabData,
  registerTabLoader,
  run,
  confirmThen,
  settleConfirm,
}

},
"./dom.js": function (module, exports, require) {
/**
 * Tiny DOM/React helpers for the client bundle (no JSX: hyperscript only).
 */
const React = require('react')

/** Hyperscript: h('div', {className}, children...) -> React.createElement. */
function h(tag, props, ...children) {
  if (props === null || props === undefined) props = {}
  const flat = []
  const push = (child) => {
    if (child === null || child === undefined || child === false) return
    if (Array.isArray(child)) {
      for (const c of child) push(c)
    } else {
      flat.push(child)
    }
  }
  for (const child of children) push(child)
  return React.createElement(tag, props, ...flat)
}

/** Join class names, skipping falsy. */
function cx(...parts) {
  return parts.filter(Boolean).join(' ')
}

/** Inline SVG icon (stroke = currentColor). */
function icon(pathData, size) {
  return h('svg', {
    className: 'gg-icon',
    width: size ?? 14,
    height: size ?? 14,
    viewBox: '0 0 16 16',
    fill: 'none',
    stroke: 'currentColor',
    strokeWidth: 1.4,
    strokeLinecap: 'round',
    strokeLinejoin: 'round',
    'aria-hidden': 'true',
  }, h('path', { d: pathData }))
}

const ICONS = {
  git: icon('M10.5 2.5 4 9m6.5-6.5 3 3m-3-3L8 0.5 16 8.5 7.5 17 0 9.5l8-8m6.5 9.5a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3Zm-13 0a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3Z', 16),
  refresh: icon('M13.5 8a5.5 5.5 0 1 1-1.6-3.9M13.5 1.5v3h-3', 13),
  close: icon('M4 4l8 8M12 4l-8 8', 13),
  check: icon('M2.5 8.5 6 12l7.5-8', 13),
  plus: icon('M8 2.5v11M2.5 8h11', 13),
  trash: icon('M2.5 4h11M6.5 4V2.5h3V4M4 4l1 9.5h6L12 4', 13),
  undo: icon('M6 4.5 2.5 8 6 11.5M3 8h7.5a4 4 0 0 1 0 8H8', 13),
  branch: icon('M4 3v5.5M12 3v5.5M4 13a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3Zm8 0a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3ZM4 11.5c0-3 8-1 8-5', 14),
  clock: icon('M8 14.5a6.5 6.5 0 1 0 0-13 6.5 6.5 0 0 0 0 13ZM8 4.5V8l2.5 1.5', 13),
  folder: icon('M1.5 3.5h4l1.5 2h7.5v7h-13v-9Z', 13),
  alert: icon('M8 14.5a6.5 6.5 0 1 0 0-13 6.5 6.5 0 0 0 0 13ZM8 5v3.5M8 11.2v.1', 13),
  down: icon('M3.5 6 8 10.5 12.5 6', 13),
  up: icon('M3.5 10 8 5.5l4.5 4.5', 13),
  chevron: icon('M5.5 3.5 10 8l-4.5 4.5', 12),
  file: icon('M3 2h6l4 4v8H3V2Zm6 0v4h4', 13),
  diff: icon('M2 12h5m3 0h4M2 8h5m3 0h4M2 4h5m3 0h4', 13),
  robot: icon('M8 1.5v3M8 14.5a3 3 0 0 0 3 3M8 14.5a3 3 0 0 1-3 3M2.5 8.5h.5a1 1 0 0 1 1 1V13a1.5 1.5 0 0 0 3 0V5a2.5 2.5 0 0 1 5 0v8a1.5 1.5 0 0 0 3 0V9.5a1 1 0 0 1 1-1h.5M8 4.5a3 3 0 0 1 0 6', 15),
  globe: icon('M8 14.5a6.5 6.5 0 1 0 0-13 6.5 6.5 0 0 0 0 13ZM1.5 8h13M8 1.5c1.8 1.8 2.7 4 2.7 6.5s-.9 4.7-2.7 6.5C6.2 12.7 5.3 10.5 5.3 8S6.2 3.3 8 1.5Z', 14),
}

module.exports = { h, cx, icon, ICONS, React }

},
"./i18n.js": function (module, exports, require) {
/**
 * Minimal zh/en dictionary for the Git panel. Defaults to Simplified Chinese;
 * flips to English when the document language starts with 'en'.
 */
const zh = {
  'panel.title': '源代码管理 (Git)',
  'panel.close': '关闭面板',
  'tab.status': '变更',
  'tab.files': '文件',
  'tab.log': '日志',
  'tab.branches': '分支',
  'tab.stash': '储藏',
  'tab.timeline': 'AI 修改',
  'files.title': '工作区文件',
  'files.search': '筛选文件…',
  'files.empty': '工作区没有文件',
  'files.tooMany': '文件过多,仅显示前 {n} 个',
  'files.clean': '该文件没有未提交的更改(显示当前内容)',
  'files.legendModified': '蓝:已修改(未提交)',
  'files.legendUntracked': '红:未跟踪(未纳入版本管理)',
  'files.legendClean': '默认色:未修改',
  'cat.title': '文件内容',
  'action.refresh': '刷新',
  'action.stageAll': '全部暂存',
  'action.unstageAll': '全部取消暂存',
  'action.commit': '提交',
  'action.aiCommit': 'AI 生成',
  'action.aiCommitTooltip': '使用大模型根据已暂存的改动自动生成提交信息',
  'action.pull': '拉取',
  'action.push': '推送',
  'action.fetch': '获取',
  'action.init': '初始化仓库',
  'action.discard': '丢弃改动',
  'action.stage': '暂存',
  'action.unstage': '取消暂存',
  'action.openDiff': '查看差异',
  'action.newBranch': '新建分支',
  'action.switch': '切换',
  'action.merge': '合并到当前分支',
  'action.revert': '撤销此提交',
  'action.pop': '恢复 (pop)',
  'action.apply': '应用 (apply)',
  'action.drop': '删除 (drop)',
  'action.stashPush': '储藏改动',
  'action.softReset': 'Soft', 'action.mixedReset': 'Mixed', 'action.hardReset': 'Hard',
  'group.staged': '已暂存',
  'group.changes': '变更',
  'group.untracked': '未跟踪',
  'group.conflicts': '合并冲突',
  'group.clean': '没有检测到改动,工作区很干净',
  'diff.title': '差异',
  'diff.empty': '选择左侧文件查看差异',
  'diff.binary': '二进制文件,无法显示文本差异',
  'diff.truncated': '输出过大已截断',
  'diff.newFile': '新文件(未跟踪)',
  'diff.tooLarge': '文件过大({size} bytes),不提供预览',
  'commit.placeholder': '提交信息 (回车提交)',
  'commit.identity': '身份:',
  'commit.identityMissing': '未配置 user.name/user.email,提交将被 git 拒绝',
  'commit.hint': '提交前请先暂存改动',
  'commit.busy': '操作进行中…',
  'commit.branch': '分支',
  'commit.detached': '分离 HEAD:当前不处于任何分支',
  'commit.noCommits': '尚无提交',
  'commit.aheadBehind': '领先 {a} / 落后 {b}',
  'branch.local': '本地分支',
  'branch.remote': '远程分支',
  'branch.create.placeholder': '新分支名称',
  'branch.current': '当前',
  'stash.placeholder': '储藏说明 (可选)',
  'stash.empty': '没有储藏记录',
  'stash.list': '储藏列表',
  'timeline.empty': '本工作区还没有 AI 文件修改记录。让 Agent 使用 write/edit 修改文件后会出现在这里。',
  'timeline.turn': '第 {turn} 轮',
  'timeline.title': 'AI 会话修改时间线',
  'timeline.session': '会话',
  'timeline.running': '当前会话正在运行,AI 可能正在修改文件;高危操作前请确认。',
  'status.notRepo': '当前目录不是 Git 仓库',
  'status.noGit': '未找到 git 可执行文件',
  'status.checking': '正在检测仓库…',
  'status.loading': '加载中…',
  'status.error': '读取状态失败',
  'status.noSession': '当前没有活动会话;切换会话后可查看其工作区。',
  'confirm.title': '确认操作',
  'confirm.dangerTitle': '危险操作确认',
  'confirm.ok': '确认',
  'confirm.cancel': '取消',
  'confirm.discardFile': '确定丢弃对 {name} 的改动?此操作不可撤销。',
  'confirm.discardFiles': '确定丢弃 {n} 个文件的改动?此操作不可撤销。',
  'confirm.cleanFile': '确定删除未跟踪文件 {name}?此操作不可撤销。',
  'confirm.cleanFiles': '确定删除 {n} 个未跟踪文件?此操作不可撤销。',
  'confirm.switch': '确定切换到分支 {name}?未提交的改动会保留。',
  'confirm.merge': '确定把 {ref} 合并到当前分支?',
  'confirm.hardReset': 'Hard reset 将丢弃 {target} 之后的所有提交和改动,不可恢复。确定继续?',
  'confirm.revert': '确定撤销提交 {commit}?',
  'confirm.dropStash': '确定删除储藏 {ref}?',
  'confirm.popStash': '确定恢复储藏 {ref}?',
  'confirm.init': '在当前目录执行 git init?',
  'toast.busy': '另一个 Git 操作正在进行,请稍候',
  'toast.done': '操作完成',
  'toast.aiCommit': '正在生成提交信息…',
  'output.title': '命令输出',
  'output.empty': '(无输出)',
  'misc.on': '于',
  'misc.paths': '个文件',
  'misc.stagedCount': '{n} 个文件已暂存',
  'misc.remote': '远程',
  'remote.addTitle': '添加远程仓库',
  'remote.name': '名称',
  'remote.url.placeholder': 'git@github.com:user/repo.git 或 https://…',
  'remote.add': '添加',
  'remote.emptyHint': '还没有配置远程仓库,添加后即可 Pull / Push',
  'remote.sshNote': '提示:SSH 地址需要本机已配置 GitHub SSH key(口令由 ssh-agent 提供)。',
}

const en = {
  'panel.title': 'Source Control (Git)',
  'panel.close': 'Close panel',
  'tab.status': 'Changes',
  'tab.files': 'Files',
  'tab.log': 'Log',
  'tab.branches': 'Branches',
  'tab.stash': 'Stash',
  'tab.timeline': 'AI Edits',
  'files.title': 'Workspace files',
  'files.search': 'Filter files…',
  'files.empty': 'No files in the workspace',
  'files.tooMany': 'Too many files — showing the first {n}',
  'files.clean': 'No uncommitted changes (showing current content)',
  'files.legendModified': 'blue: modified (uncommitted)',
  'files.legendUntracked': 'red: untracked',
  'files.legendClean': 'default: unmodified',
  'cat.title': 'File content',
  'action.refresh': 'Refresh',
  'action.stageAll': 'Stage all',
  'action.unstageAll': 'Unstage all',
  'action.commit': 'Commit',
  'action.aiCommit': 'AI Gen',
  'action.aiCommitTooltip': 'Generate commit message from staged changes using LLM',
  'action.pull': 'Pull',
  'action.push': 'Push',
  'action.fetch': 'Fetch',
  'action.init': 'Initialize repository',
  'action.discard': 'Discard changes',
  'action.stage': 'Stage',
  'action.unstage': 'Unstage',
  'action.openDiff': 'Open diff',
  'action.newBranch': 'New branch',
  'action.switch': 'Switch',
  'action.merge': 'Merge into current branch',
  'action.revert': 'Revert this commit',
  'action.pop': 'Pop',
  'action.apply': 'Apply',
  'action.drop': 'Drop',
  'action.stashPush': 'Stash changes',
  'action.softReset': 'Soft', 'action.mixedReset': 'Mixed', 'action.hardReset': 'Hard',
  'group.staged': 'Staged',
  'group.changes': 'Changes',
  'group.untracked': 'Untracked',
  'group.conflicts': 'Merge conflicts',
  'group.clean': 'No changes detected — the working tree is clean',
  'diff.title': 'Diff',
  'diff.empty': 'Select a file on the left to view its diff',
  'diff.binary': 'Binary file: no text diff available',
  'diff.truncated': 'Output truncated (too large)',
  'diff.newFile': 'New file (untracked)',
  'diff.tooLarge': 'File too large ({size} bytes): no preview',
  'commit.placeholder': 'Commit message (Enter to commit)',
  'commit.identity': 'Identity:',
  'commit.identityMissing': 'user.name / user.email not configured; git will refuse to commit',
  'commit.hint': 'Stage changes before committing',
  'commit.busy': 'Operation in progress…',
  'commit.branch': 'Branch',
  'commit.detached': 'Detached HEAD: not on any branch',
  'commit.noCommits': 'No commits yet',
  'commit.aheadBehind': 'ahead {a} / behind {b}',
  'branch.local': 'Local branches',
  'branch.remote': 'Remote branches',
  'branch.create.placeholder': 'New branch name',
  'branch.current': 'current',
  'stash.placeholder': 'Stash message (optional)',
  'stash.empty': 'No stashes',
  'stash.list': 'Stash list',
  'timeline.empty': 'No AI file edits recorded for this workspace yet. write/edit tool calls will show up here.',
  'timeline.turn': 'turn {turn}',
  'timeline.title': 'AI session edit timeline',
  'timeline.session': 'session',
  'timeline.running': 'The current session is running — the agent may be editing files; be careful with destructive operations.',
  'status.notRepo': 'The current directory is not a Git repository',
  'status.noGit': 'git executable not found',
  'status.checking': 'Detecting repository…',
  'status.loading': 'Loading…',
  'status.error': 'Failed to read status',
  'status.noSession': 'No active session; pick one to inspect its workspace.',
  'confirm.title': 'Confirm',
  'confirm.dangerTitle': 'Destructive operation',
  'confirm.ok': 'Confirm',
  'confirm.cancel': 'Cancel',
  'confirm.discardFile': 'Discard changes to {name}? This cannot be undone.',
  'confirm.discardFiles': 'Discard changes to {n} files? This cannot be undone.',
  'confirm.cleanFile': 'Delete untracked file {name}? This cannot be undone.',
  'confirm.cleanFiles': 'Delete {n} untracked files? This cannot be undone.',
  'confirm.switch': 'Switch to branch {name}? Uncommitted changes are kept.',
  'confirm.merge': 'Merge {ref} into the current branch?',
  'confirm.hardReset': 'Hard reset discards all commits and changes after {target}. This is irreversible. Continue?',
  'confirm.revert': 'Revert commit {commit}?',
  'confirm.dropStash': 'Drop stash {ref}?',
  'confirm.popStash': 'Pop stash {ref}?',
  'confirm.init': 'Run git init in the current directory?',
  'toast.busy': 'Another Git operation is in progress',
  'toast.done': 'Done',
  'toast.aiCommit': 'Generating commit message…',
  'output.title': 'Command output',
  'output.empty': '(no output)',
  'misc.on': 'on',
  'misc.paths': 'files',
  'misc.stagedCount': '{n} staged',
  'misc.remote': 'Remotes',
  'remote.addTitle': 'Add remote repository',
  'remote.name': 'Name',
  'remote.url.placeholder': 'git@github.com:user/repo.git or https://…',
  'remote.add': 'Add',
  'remote.emptyHint': 'No remote configured yet — add one to pull / push',
  'remote.sshNote': 'Note: SSH URLs require a GitHub SSH key on this machine (passphrase via ssh-agent).',
}

let lang = 'zh'
if (typeof document !== 'undefined') {
  const htmlLang = document.documentElement?.lang ?? ''
  if (htmlLang.toLowerCase().startsWith('en')) lang = 'en'
}

function t(key, params) {
  const dict = lang === 'en' ? en : zh
  let text = dict[key] ?? zh[key] ?? key
  if (params) {
    for (const [k, v] of Object.entries(params)) text = text.split(`{${k}}`).join(String(v))
  }
  return text
}

module.exports = { t, lang }

},
"./index.js": function (module, exports, require) {
/**
 * Browser half of dsh-git-gui — the plugin body exported to the web shell.
 *
 * The micro-bundler wraps the whole client-src tree into the
 * `window.__ModuleLoader__.load({ id, factory })` CJS shape; the shell
 * materializes this module and treats its exports as a cordis object plugin.
 * `./pkg-id` is a synthetic module the bundler generates from package.json.
 */

const { startController } = require('./control')
const { makeGitApi } = require('./api')
const { FooterButton } = require('./v-footer')
const { GitPanel } = require('./v-panel')
const { css } = require('./styles')
const PKG_ID = require('./pkg-id')

const inject = ['connection', 'slots']

function apply(ctx) {
  // plugin-owned stylesheet; the module loader inventories this tag id so the
  // HMR driver can remove it together with the plugin.
  if (typeof document !== 'undefined') {
    const tagId = `${PKG_ID}/styles.css`
    if (document.querySelector(`style[data-plugin-css="${tagId}"]`) === null) {
      const tag = document.createElement('style')
      tag.dataset.plugin = PKG_ID
      tag.dataset.pluginCss = tagId
      tag.textContent = css
      document.head.appendChild(tag)
    }
  }

  const api = makeGitApi(ctx.connection)
  startController(api)

  ctx.effect(() => {
    const disposeFooter = ctx.slots.inject('sidebar.footer.action', () => ctx.slots.register(
      { name: 'sidebar.footer.action', id: 'dsh-git-gui', order: 20 },
      (props) => FooterButton(props),
    ))
    const disposePanel = ctx.slots.inject('shell.overlay', () => ctx.slots.register(
      { name: 'shell.overlay', id: 'dsh-git-gui' },
      (props) => GitPanel(props),
    ))
    return () => {
      disposeFooter()
      disposePanel()
    }
  })
}

module.exports = { apply, inject }
// test-only store access (used by tests/client.test.mjs smoke tests)
module.exports.__test = { setState: require('./store').setState, getState: require('./store').getState }

},
"./store.js": function (module, exports, require) {
/**
 * Tiny observable store for the Git panel (useSyncExternalStore-based).
 */
const React = require('react')

const initial = {
  open: false,
  tab: 'status',
  busy: false,
  busyLabel: '',
  cwd: null,          // absolute workspace root of the current session
  sessionId: null,
  sessionRunning: false,
  check: null,        // {repo, root, gitVersion}
  status: null,       // {branch, files}
  statusError: null,
  selected: null,     // {path, staged, untracked, cat}
  diff: null,         // {path, staged, untracked, cat, loading, error, data}
  commits: [],
  logError: null,
  refs: [],
  refsError: null,
  stashes: [],
  stashError: null,
  activity: [],
  identity: null,
  tree: null,          // {files:[{path,state}], truncated, total}
  treeError: null,
  remotes: [],         // [{name, fetch?, push?}]
  remoteModal: false,  // "添加远程仓库" 弹窗
  commitMsg: '',
  output: null,       // {title, text}
  confirm: null,      // {body, danger, action}
  toast: null,        // {kind, text}
}

let state = initial
const listeners = new Set()

function getState() {
  return state
}

function setState(patch) {
  state = { ...state, ...patch }
  for (const listener of listeners) listener()
}

function resetWorkspace(cwd, sessionId) {
  state = {
    ...initial,
    cwd,
    sessionId,
    sessionRunning: state.sessionRunning,
    open: state.open,
    tab: state.tab,
    commitMsg: state.commitMsg,
  }
  for (const listener of listeners) listener()
}

function subscribe(listener) {
  listeners.add(listener)
  return () => listeners.delete(listener)
}

function useStore(selector) {
  const ref = React.useRef(undefined)
  const getSnapshot = React.useCallback(() => {
    const next = selector(state)
    if (next !== ref.current) ref.current = next
    return ref.current
  }, [selector])
  return React.useSyncExternalStore(subscribe, getSnapshot, getSnapshot)
}

/** Convenience hook: open flag. */
function useOpen() {
  return useStore((s) => s.open)
}

module.exports = { getState, setState, resetWorkspace, subscribe, useStore, useOpen }

},
"./styles.js": function (module, exports, require) {
/**
 * Panel stylesheet, injected as a plugin-owned <style> tag at
 * materialization. Colors ride the shared theme tokens so light/dark both
 * work; every class is `gg-` prefixed to avoid collisions.
 */
const css = `
/* text on accent fills: brand/state tokens flip to LIGHT shades in dark
   mode (brand-primary = near-white), so fixed white text became invisible;
   this variable flips together with the shell's dark-theme attribute and is
   defined at body level because the sidebar badge lives outside the panel. */
body { --gg-on-accent: #ffffff; }
body[data-ds-dark-theme] { --gg-on-accent: #10141b; }
.gg-panel {
  position: absolute; top: 12px; right: 12px; bottom: 12px;
  display: flex; flex-direction: column;
  background: var(--dsw-alias-bg-layer-1);
  border: 1px solid var(--dsw-alias-border-l2);
  border-radius: 12px;
  box-shadow: 0 12px 40px rgba(0,0,0,.28);
  overflow: hidden;
  pointer-events: auto;
  z-index: 1;
  font-size: 12.5px;
  color: var(--dsw-alias-label-primary);
}
.gg-resize {
  position: absolute; left: -3px; top: 0; bottom: 0; width: 7px;
  cursor: col-resize; z-index: 3;
}
.gg-resize:hover { background: var(--dsw-alias-interactive-bg-hover); }
.gg-panel-head {
  display: flex; align-items: center; gap: 8px;
  padding: 8px 10px 6px 14px;
  border-bottom: 1px solid var(--dsw-alias-border-l1);
}
.gg-panel-title { font-weight: 600; flex: 1; }
.gg-icon-btn {
  display: inline-flex; align-items: center; justify-content: center;
  width: 26px; height: 26px; border: none; border-radius: 6px;
  background: transparent; color: var(--dsw-alias-label-secondary);
  cursor: pointer; padding: 0; flex: none;
}
.gg-icon-btn:hover { background: var(--dsw-alias-interactive-bg-hover); color: var(--dsw-alias-label-primary); }
.gg-icon-btn:disabled { opacity: .4; cursor: default; }
.gg-btn {
  display: inline-flex; align-items: center; justify-content: center; gap: 5px;
  border: 1px solid var(--dsw-alias-border-l2); border-radius: 6px;
  background: var(--dsw-alias-bg-layer-2); color: var(--dsw-alias-label-primary);
  font-size: 12px; padding: 4px 10px; cursor: pointer; white-space: nowrap;
}
.gg-btn:hover { background: var(--dsw-alias-interactive-bg-hover); }
.gg-btn:disabled { opacity: .45; cursor: default; }
.gg-btn-primary {
  background: var(--dsw-alias-brand-primary); border-color: transparent; color: var(--gg-on-accent);
}
.gg-btn-primary:hover { filter: brightness(1.08); background: var(--dsw-alias-brand-primary); color: var(--gg-on-accent); }
.gg-btn-danger { background: var(--dsw-alias-state-error-primary); border-color: transparent; color: var(--gg-on-accent); }
.gg-mini-btn {
  border: 1px solid var(--dsw-alias-border-l2); border-radius: 5px;
  background: transparent; color: var(--dsw-alias-label-secondary);
  font-size: 11px; padding: 1px 7px; cursor: pointer;
  display: inline-flex; align-items: center; gap: 4px;
}
.gg-mini-btn:hover { background: var(--dsw-alias-interactive-bg-hover); color: var(--dsw-alias-label-primary); }
.gg-mini-btn:disabled { opacity: .4; cursor: default; }
.gg-mini-danger:hover { color: var(--dsw-alias-state-error-primary); }
.gg-row-btn { width: 22px; height: 22px; opacity: 0; }
.gg-file:hover .gg-row-btn, .gg-log-row:hover .gg-row-btn { opacity: 1; }

.gg-banner {
  display: flex; align-items: center; gap: 6px;
  margin: 6px 10px 0; padding: 5px 9px;
  border-radius: 7px; font-size: 11.5px;
  background: color-mix(in srgb, var(--dsw-alias-state-warn-primary) 14%, transparent);
  color: var(--dsw-alias-label-primary);
}
.gg-banner .gg-icon { flex: none; color: var(--dsw-alias-state-warn-primary); }

.gg-wsbar {
  display: flex; align-items: center; gap: 7px;
  padding: 7px 10px 7px 14px;
  border-bottom: 1px solid var(--dsw-alias-border-l1);
  color: var(--dsw-alias-label-secondary); font-size: 12px;
}
.gg-ws-name { display: inline-flex; align-items: center; gap: 5px; max-width: 150px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.gg-ws-branch { display: inline-flex; align-items: center; gap: 4px; color: var(--dsw-alias-brand-primary); max-width: 140px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.gg-ws-detached { color: var(--dsw-alias-state-warn-primary); }
.gg-ws-ab { font-size: 11px; }
.gg-ws-busy { color: var(--dsw-alias-brand-primary); font-size: 11px; }
.gg-spacer { flex: 1; }

.gg-tabs { display: flex; flex-direction: column; flex: 1; min-height: 0; }
.gg-tabbar {
  display: flex; gap: 2px; padding: 5px 10px 0;
  border-bottom: 1px solid var(--dsw-alias-border-l1);
  overflow-x: auto; flex: none;
}
.gg-tab {
  border: none; background: transparent; cursor: pointer;
  color: var(--dsw-alias-label-secondary); font-size: 12px;
  padding: 6px 9px; border-bottom: 2px solid transparent; white-space: nowrap;
}
.gg-tab:hover { color: var(--dsw-alias-label-primary); }
.gg-tab-active { color: var(--dsw-alias-label-primary); border-bottom-color: var(--dsw-alias-brand-primary); font-weight: 600; }
.gg-tabbody { flex: 1; min-height: 0; display: flex; flex-direction: column; }
.gg-panel-body { flex: 1; min-height: 0; display: flex; flex-direction: column; }

.gg-empty {
  display: flex; flex-direction: column; align-items: center; justify-content: center;
  gap: 8px; padding: 26px 14px; text-align: center;
  color: var(--dsw-alias-label-secondary); flex: 1;
}
.gg-empty-err { color: var(--dsw-alias-state-error-primary); }
.gg-empty-title { font-weight: 600; color: var(--dsw-alias-label-primary); }

.gg-status { display: flex; flex-direction: column; flex: 1; min-height: 0; }
.gg-commit { padding: 8px 10px; border-bottom: 1px solid var(--dsw-alias-border-l1); flex: none; }
.gg-commit-input {
  width: 100%; box-sizing: border-box; resize: vertical;
  background: var(--dsw-alias-bg-layer-2);
  border: 1px solid var(--dsw-alias-border-l2); border-radius: 7px;
  color: var(--dsw-alias-label-primary); font: inherit; padding: 6px 8px;
}
.gg-commit-input:focus { outline: 1px solid var(--dsw-alias-brand-primary); }
.gg-commit-foot { display: flex; align-items: center; gap: 6px; margin-top: 6px; }
.gg-identity { font-size: 11px; color: var(--dsw-alias-label-secondary); max-width: 40%; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.gg-identity-missing { color: var(--dsw-alias-state-warn-primary); }
.gg-status-main { display: flex; flex-direction: column; flex: 1; min-height: 0; }
.gg-files { flex: 1 1 45%; min-height: 90px; overflow-y: auto; }

.gg-group { border-bottom: 1px solid var(--dsw-alias-border-l1); }
.gg-group-head {
  display: flex; align-items: center; gap: 7px;
  padding: 5px 12px 4px; font-weight: 600; font-size: 11px;
  color: var(--dsw-alias-label-secondary); position: sticky; top: 0;
  background: var(--dsw-alias-bg-layer-1); z-index: 1;
}
.gg-group-name { font-weight: 600; font-size: 11px; color: var(--dsw-alias-label-secondary); }
.gg-group-count { font-weight: 400; }
.gg-group-body { display: flex; flex-direction: column; }

.gg-file {
  display: flex; align-items: center; gap: 7px;
  padding: 3px 10px; cursor: pointer;
}
.gg-file:hover { background: var(--dsw-alias-interactive-bg-hover); }
.gg-file-conflict .gg-file-name { color: var(--dsw-alias-state-error-primary); }
.gg-letter {
  flex: none; width: 17px; height: 17px; border: none; border-radius: 4px;
  font-size: 11px; font-weight: 700; color: var(--gg-on-accent); cursor: pointer;
  display: inline-flex; align-items: center; justify-content: center;
}
.gg-l-m { background: var(--dsw-alias-brand-primary); }
.gg-l-a { background: var(--dsw-alias-state-success-primary); }
.gg-l-d { background: var(--dsw-alias-state-error-primary); }
.gg-l-r { background: var(--dsw-alias-state-warn-primary); }
.gg-l-c { background: var(--dsw-alias-state-warn-primary); }
.gg-l-u { background: var(--dsw-alias-state-error-primary); }
.gg-l-q { background: var(--dsw-alias-label-secondary); }
.gg-l-t { background: var(--dsw-alias-label-secondary); }
.gg-file-main { display: flex; min-width: 0; flex: 1; }
.gg-file-dir { color: var(--dsw-alias-label-secondary); }
.gg-file-name { font-weight: 500; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.gg-file-renamed { color: var(--dsw-alias-label-secondary); font-size: 11px; margin-left: 6px; }

.gg-diff { flex: 1 1 55%; min-height: 120px; display: flex; flex-direction: column; border-top: 1px solid var(--dsw-alias-border-l2); }
.gg-diff-head {
  display: flex; align-items: center; gap: 7px; padding: 5px 12px;
  border-bottom: 1px solid var(--dsw-alias-border-l1); flex: none;
  font-weight: 600; font-size: 11.5px;
}
.gg-diff-path { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; flex: 1; }
.gg-diff-rename { color: var(--dsw-alias-label-secondary); font-weight: 400; font-size: 11px; }
.gg-chip {
  border: 1px solid var(--dsw-alias-border-l2); border-radius: 999px;
  font-size: 10.5px; padding: 0 7px; color: var(--dsw-alias-label-secondary);
  white-space: nowrap; flex: none;
}
.gg-diff-scroll { flex: 1; overflow: auto; }
.gg-hunks { font-family: ui-monospace, 'Cascadia Mono', Consolas, monospace; font-size: 11.5px; }
.gg-hunk-head { padding: 4px 10px; color: var(--dsw-alias-label-secondary); background: var(--dsw-alias-bg-layer-2); position: sticky; top: 0; }
.gg-line { display: flex; align-items: baseline; white-space: pre; padding: 0 10px; min-width: max-content; }
.gg-line-no { flex: none; width: 34px; text-align: right; color: var(--dsw-alias-label-secondary); font-size: 10.5px; user-select: none; padding-right: 8px; }
.gg-line-mark { flex: none; width: 14px; text-align: center; user-select: none; }
.gg-line-text { flex: 1; }
.gg-line-add { background: color-mix(in srgb, var(--dsw-alias-state-success-primary) 11%, transparent); }
.gg-line-add .gg-line-mark { color: var(--dsw-alias-state-success-primary); }
.gg-line-del { background: color-mix(in srgb, var(--dsw-alias-state-error-primary) 11%, transparent); }
.gg-line-del .gg-line-mark { color: var(--dsw-alias-state-error-primary); }
.gg-line-nonl { color: var(--dsw-alias-state-warn-primary); margin-left: 6px; }

.gg-log { overflow-y: auto; flex: 1; }
.gg-log-row { display: flex; align-items: center; gap: 6px; padding: 7px 10px; border-bottom: 1px solid var(--dsw-alias-border-l1); }
.gg-log-row:hover { background: var(--dsw-alias-interactive-bg-hover); }
.gg-log-main { flex: 1; min-width: 0; display: flex; flex-direction: column; gap: 2px; }
.gg-log-subject { font-weight: 600; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.gg-log-meta { display: flex; align-items: center; gap: 7px; font-size: 11px; color: var(--dsw-alias-label-secondary); }
.gg-log-hash { font-family: ui-monospace, Consolas, monospace; }

.gg-branches { overflow-y: auto; flex: 1; padding-bottom: 12px; }
.gg-branch-actions { display: flex; flex-wrap: wrap; gap: 6px; padding: 8px 10px; }
.gg-branch-new { display: flex; gap: 6px; padding: 0 10px 8px; }
.gg-input {
  flex: 1; min-width: 0; background: var(--dsw-alias-bg-layer-2);
  border: 1px solid var(--dsw-alias-border-l2); border-radius: 6px;
  color: var(--dsw-alias-label-primary); font: inherit; padding: 5px 8px;
}
.gg-input:focus { outline: 1px solid var(--dsw-alias-brand-primary); }
.gg-ref-group { padding: 6px 10px 4px; }
.gg-ref-row { display: flex; align-items: center; gap: 7px; padding: 3px 0; }
.gg-ref-current { font-weight: 600; }
.gg-ref-name {
  display: inline-flex; align-items: center; gap: 6px; flex: 1; min-width: 0;
  border: none; background: transparent; color: inherit; font: inherit;
  text-align: left; cursor: pointer; padding: 2px 0; overflow: hidden;
}
.gg-ref-name:hover:not(:disabled) { color: var(--dsw-alias-brand-primary); }
.gg-ref-name:disabled { cursor: default; }
.gg-ref-upstream { color: var(--dsw-alias-label-secondary); font-size: 11px; font-weight: 400; }
.gg-remote-row { display: flex; gap: 8px; padding: 2px 0; }
.gg-remote-url { color: var(--dsw-alias-label-secondary); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }

.gg-stash { overflow-y: auto; flex: 1; }
.gg-stash-new { display: flex; gap: 6px; padding: 8px 10px; }
.gg-stash-list { padding: 0 10px 8px; }
.gg-stash-row { display: flex; align-items: center; gap: 7px; padding: 4px 0; border-bottom: 1px solid var(--dsw-alias-border-l1); }
.gg-stash-ref { font-family: ui-monospace, Consolas, monospace; font-size: 11px; flex: none; }
.gg-stash-subject { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }

.gg-timeline { overflow-y: auto; flex: 1; padding: 6px 10px; }
.gg-tl-row {
  display: flex; align-items: center; gap: 8px; width: 100%;
  border: none; border-bottom: 1px solid var(--dsw-alias-border-l1);
  background: transparent; color: inherit; font: inherit; text-align: left;
  padding: 6px 2px; cursor: pointer;
}
.gg-tl-row:hover { background: var(--dsw-alias-interactive-bg-hover); }
.gg-tl-tool {
  flex: none; border: 1px solid var(--dsw-alias-border-l2); border-radius: 4px;
  font-size: 10px; padding: 0 5px; color: var(--dsw-alias-label-secondary);
  font-family: ui-monospace, Consolas, monospace;
}
.gg-tl-path { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; font-weight: 500; }
.gg-tl-meta { flex: none; font-size: 10.5px; color: var(--dsw-alias-label-secondary); }

/* workspace file tree */
.gg-files-view { display: flex; flex-direction: column; flex: 1; min-height: 0; }
.gg-files-toolbar {
  display: flex; align-items: center; gap: 10px; padding: 7px 10px;
  border-bottom: 1px solid var(--dsw-alias-border-l1); flex: none;
}
.gg-files-legend { display: flex; gap: 10px; flex: none; font-size: 10.5px; color: var(--dsw-alias-label-secondary); }
.gg-legend-item { display: inline-flex; align-items: center; gap: 4px; white-space: nowrap; }
.gg-swatch { width: 9px; height: 9px; border-radius: 2px; display: inline-block; flex: none; }
.gg-swatch-mod { background: var(--dsw-alias-state-business-primary, #3964fe); }
.gg-swatch-unt { background: var(--dsw-alias-state-error-primary, #dc2626); }
.gg-swatch-clean { background: var(--dsw-alias-label-primary); }
.gg-files-tree { flex: 1; overflow: auto; padding-bottom: 8px; }
.gg-files-note { padding: 4px 10px 8px; font-size: 11px; color: var(--dsw-alias-label-secondary); }
.gg-tree-row {
  display: flex; align-items: center; gap: 5px;
  padding: 2.5px 10px; cursor: pointer; min-width: 0;
}
.gg-tree-row:hover { background: var(--dsw-alias-interactive-bg-hover); }
.gg-tree-dir { color: var(--dsw-alias-label-secondary); }
.gg-tree-file { color: var(--dsw-alias-label-primary); }
.gg-tree-file.gg-tree-modified { color: var(--dsw-alias-state-business-primary, #3964fe); }
.gg-tree-file.gg-tree-untracked { color: var(--dsw-alias-state-error-primary, #dc2626); }
.gg-tree-toggle {
  flex: none; width: 16px; height: 16px; border: none; background: transparent;
  color: inherit; cursor: pointer; padding: 0;
  display: inline-flex; align-items: center; justify-content: center;
}
.gg-tree-chevron { display: inline-flex; transition: transform .12s ease; }
.gg-tree-chevron-closed { transform: rotate(-90deg); }
.gg-tree-name { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }

.gg-output { border-top: 1px solid var(--dsw-alias-border-l1); flex: none; }
.gg-output-head {
  display: flex; align-items: center; gap: 6px; width: 100%;
  border: none; background: transparent; color: var(--dsw-alias-label-secondary);
  font: inherit; font-size: 11px; padding: 5px 12px; cursor: pointer;
}
.gg-output-head:hover { background: var(--dsw-alias-interactive-bg-hover); }
.gg-output-title { flex: 1; text-align: left; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.gg-output-body {
  margin: 0 12px 10px; padding: 8px; max-height: 130px; overflow: auto;
  background: var(--dsw-alias-bg-layer-2); border-radius: 7px;
  font-family: ui-monospace, Consolas, monospace; font-size: 11px;
  white-space: pre-wrap; word-break: break-all;
}

.gg-modal-backdrop {
  position: absolute; inset: 0; background: rgba(0,0,0,.45);
  display: flex; align-items: center; justify-content: center; z-index: 6;
}
.gg-modal {
  width: min(380px, calc(100% - 40px)); background: var(--dsw-alias-bg-layer-1);
  border: 1px solid var(--dsw-alias-border-l2); border-radius: 12px;
  padding: 14px; display: flex; flex-direction: column; gap: 10px;
  box-shadow: 0 16px 50px rgba(0,0,0,.35);
}
.gg-modal-danger { border-color: var(--dsw-alias-state-error-primary); }
.gg-modal-title { display: flex; align-items: center; gap: 8px; font-weight: 700; font-size: 13px; }
.gg-modal-danger .gg-modal-title { color: var(--dsw-alias-state-error-primary); }
.gg-modal-body { font-size: 12.5px; color: var(--dsw-alias-label-secondary); word-break: break-all; }
.gg-modal-actions { display: flex; justify-content: flex-end; gap: 8px; }
.gg-field { display: flex; flex-direction: column; gap: 4px; }
.gg-field-label { font-size: 11px; color: var(--dsw-alias-label-secondary); }
.gg-icon-warn { color: var(--dsw-alias-state-warn-primary); }

.gg-toast {
  position: absolute; left: 12px; right: 12px; bottom: 12px; z-index: 7;
  padding: 8px 12px; border-radius: 8px; font-size: 12px;
  background: var(--dsw-alias-bg-overlay);
  border: 1px solid var(--dsw-alias-border-l2);
  box-shadow: 0 8px 24px rgba(0,0,0,.3);
  word-break: break-all;
}
.gg-toast-err { border-color: var(--dsw-alias-state-error-primary); color: var(--dsw-alias-state-error-primary); }
.gg-toast-warn { border-color: var(--dsw-alias-state-warn-primary); color: var(--dsw-alias-state-warn-primary); }

/* sidebar footer entry */
.gg-footer-btn {
  display: flex; align-items: center; gap: 8px; flex: 1; min-width: 0;
  border: none; background: transparent; cursor: pointer;
  color: var(--dsw-alias-label-secondary); font: inherit; font-size: 12px;
  padding: 0 6px; height: 36px; border-radius: 8px; position: relative;
}
.gg-footer-btn:hover { background: var(--dsw-alias-interactive-bg-hover); color: var(--dsw-alias-label-primary); }
.gg-footer-btn.gg-active { color: var(--dsw-alias-label-primary); background: var(--dsw-alias-interactive-bg-hover); }
.gg-footer-icon { display: inline-flex; align-items: center; justify-content: center; }
.gg-footer-marks { display: inline-flex; gap: 3px; align-items: center; }
.gg-badge {
  min-width: 15px; height: 15px; padding: 0 4px; border-radius: 999px;
  background: var(--dsw-alias-brand-primary); color: var(--gg-on-accent);
  font-size: 10px; font-weight: 700;
  display: inline-flex; align-items: center; justify-content: center;
  box-sizing: border-box;
}
.gg-badge-err { background: var(--dsw-alias-state-error-primary); }

.gg-icon { flex: none; }
`

module.exports = { css }

},
"./v-branch.js": function (module, exports, require) {
/**
 * Branches view: local/remote refs, switch/create, merge, pull/push/fetch.
 */
const { h, cx, ICONS, React } = require('./dom')
const { useStore, setState } = require('./store')
const { t } = require('./i18n')
const { run, confirmThen, getApi, registerTabLoader } = require('./control')

function BranchView() {
  const refs = useStore((s) => s.refs)
  const remotes = useStore((s) => s.remotes)
  const refsError = useStore((s) => s.refsError)
  const cwd = useStore((s) => s.cwd)
  const busy = useStore((s) => s.busy)
  const branch = useStore((s) => s.status?.branch)
  const [newName, setNewName] = React.useState('')

  React.useEffect(() => {
    registerTabLoader('branches', async (w) => {
      const result = await getApi().branches(w)
      setState({ refs: result.refs, remotes: result.remotes, refsError: null })
    })
    if (cwd !== null) {
      getApi().branches(cwd).then((r) => setState({ refs: r.refs, remotes: r.remotes, refsError: null }))
        .catch((e) => setState({ refs: [], remotes: [], refsError: e.message }))
    }
  }, [cwd])

  const local = refs.filter((r) => !r.name.includes('/') && !r.name.startsWith('remotes/'))
  const remote = refs.filter((r) => r.name.includes('/'))

  const doSwitch = (name) => {
    confirmThen({
      body: t('confirm.switch', { name }),
      action: () => run(t('action.switch'), () => getApi().switchBranch(cwd, name, false)),
    })
  }
  const doMerge = (name) => {
    confirmThen({
      body: t('confirm.merge', { ref: name }),
      action: () => run(t('action.merge'), () => getApi().merge(cwd, name)),
    })
  }
  const doCreate = () => {
    const name = newName.trim()
    if (name === '') return
    run(t('action.newBranch'), () => getApi().switchBranch(cwd, name, true)).then((ok) => {
      if (ok) setNewName('')
    })
  }
  const doPull = (mode) => run(`${t('action.pull')} (${mode})`, () => getApi().pull(cwd, mode))
  const doPush = () => run(t('action.push'), () => getApi().push(cwd))
  const doFetch = () => run(t('action.fetch'), () => getApi().fetch(cwd))

  const row = (r, kind) => h('div', {
    className: cx('gg-ref-row', r.current && 'gg-ref-current'),
    key: r.name,
    title: r.name,
  },
    h('button', {
      type: 'button',
      className: 'gg-ref-name',
      disabled: busy || r.current,
      onClick: () => (kind === 'local' ? doSwitch(r.name) : undefined),
    },
      ICONS.branch,
      h('span', {}, r.name),
      r.current && h('span', { className: 'gg-chip' }, t('branch.current')),
      r.upstream && h('span', { className: 'gg-ref-upstream' }, `→ ${r.upstream}${r.track ? ` [${r.track}]` : ''}`)),
    !r.current && kind === 'local' && h('button', {
      type: 'button',
      className: 'gg-mini-btn',
      disabled: busy,
      onClick: () => doMerge(r.name),
    }, t('action.merge')))

  return h('div', { className: 'gg-branches' },
    h('div', { className: 'gg-branch-actions' },
      h('button', { type: 'button', className: 'gg-btn', disabled: busy, onClick: () => doPull('ff-only') }, 'Pull (ff)'),
      h('button', { type: 'button', className: 'gg-btn', disabled: busy, onClick: () => doPull('merge') }, 'Pull (merge)'),
      h('button', { type: 'button', className: 'gg-btn', disabled: busy, onClick: () => doPull('rebase') }, 'Pull (rebase)'),
      h('button', { type: 'button', className: 'gg-btn', disabled: busy, onClick: doPush }, t('action.push')),
      h('button', { type: 'button', className: 'gg-btn', disabled: busy, onClick: doFetch }, t('action.fetch'))),
    refsError && h('div', { className: 'gg-empty gg-empty-err' }, refsError),
    branch?.detached && h('div', { className: 'gg-banner' }, t('commit.detached')),
    h('div', { className: 'gg-branch-new' },
      h('input', {
        className: 'gg-input',
        value: newName,
        placeholder: t('branch.create.placeholder'),
        onChange: (e) => setNewName(e.target.value),
        onKeyDown: (e) => { if (e.key === 'Enter') doCreate() },
      }),
      h('button', { type: 'button', className: 'gg-btn gg-btn-primary', disabled: busy || newName.trim() === '', onClick: doCreate }, t('action.newBranch'))),
    h('div', { className: 'gg-ref-group' },
      h('div', { className: 'gg-group-name' }, t('branch.local')),
      local.map((r) => row(r, 'local'))),
    remote.length > 0 && h('div', { className: 'gg-ref-group' },
      h('div', { className: 'gg-group-name' }, t('branch.remote')),
      remote.map((r) => row(r, 'remote'))),
    remotes.length > 0 && h('div', { className: 'gg-ref-group' },
      h('div', { className: 'gg-group-name' }, t('misc.remote')),
      remotes.map((r) => h('div', { className: 'gg-remote-row', key: r.name },
        h('span', {}, r.name), h('span', { className: 'gg-remote-url' }, r.fetch ?? r.push ?? '')))),
  )
}

module.exports = { BranchView }

},
"./v-files.js": function (module, exports, require) {
/**
 * Workspace file tree view: every tracked/untracked (non-ignored) file with
 * a git-state color — default (theme text) = unmodified, blue = modified
 * uncommitted, red = untracked. Clicking opens the diff / content preview.
 */
const { h, cx, ICONS, React } = require('./dom')
const { useStore, setState } = require('./store')
const { t } = require('./i18n')
const { getApi, registerTabLoader, refreshDiff } = require('./control')

const MAX_RENDER_ROWS = 800

function buildTree(files, filter) {
  const root = { dirs: new Map(), files: [] }
  const needle = (filter ?? '').trim().toLowerCase()
  for (const file of files) {
    if (needle !== '' && !file.path.toLowerCase().includes(needle)) continue
    const segments = file.path.split('/')
    const name = segments.pop()
    let node = root
    for (const segment of segments) {
      if (!node.dirs.has(segment)) node.dirs.set(segment, { dirs: new Map(), files: [] })
      node = node.dirs.get(segment)
    }
    node.files.push({ name, path: file.path, state: file.state })
  }
  return root
}

function Row({ node, depth, collapsed, onToggle, onOpen, path, rendered }) {
  if (rendered.count >= MAX_RENDER_ROWS) return null
  const rows = []
  const dirs = [...node.dirs.entries()].sort((a, b) => a[0].localeCompare(b[0]))
  for (const [name, child] of dirs) {
    const childPath = path === '' ? name : `${path}/${name}`
    const isCollapsed = collapsed.has(childPath)
    rows.push(h('div', { className: 'gg-tree-row gg-tree-dir', key: `d:${childPath}`, style: { paddingLeft: `${8 + depth * 14}px` } },
      h('button', {
        type: 'button',
        className: 'gg-tree-toggle',
        onClick: () => onToggle(childPath, isCollapsed),
        title: isCollapsed ? '展开' : '折叠',
      }, h('span', { className: cx('gg-tree-chevron', isCollapsed && 'gg-tree-chevron-closed') }, ICONS.chevron)),
      ICONS.folder,
      h('span', { className: 'gg-tree-name' }, name)))
    if (!isCollapsed) {
      rows.push(h(Row, { node: child, depth: depth + 1, collapsed, onToggle, onOpen, path: childPath, rendered, key: `r:${childPath}` }))
    }
  }
  for (const file of [...node.files].sort((a, b) => a.name.localeCompare(b.name))) {
    if (rendered.count >= MAX_RENDER_ROWS) break
    rendered.count++
    rows.push(h('div', {
      className: cx('gg-tree-row gg-tree-file',
        file.state === 'modified' && 'gg-tree-modified',
        file.state === 'untracked' && 'gg-tree-untracked'),
      key: `f:${file.path}`,
      style: { paddingLeft: `${8 + depth * 14 + 18}px` },
      title: file.path,
      onClick: () => onOpen(file),
    },
      ICONS.file,
      h('span', { className: 'gg-tree-name' }, file.name)))
  }
  return rows
}

function Legend() {
  return h('div', { className: 'gg-files-legend' },
    h('span', { className: 'gg-legend-item' }, h('span', { className: 'gg-swatch gg-swatch-mod' }), t('files.legendModified')),
    h('span', { className: 'gg-legend-item' }, h('span', { className: 'gg-swatch gg-swatch-unt' }), t('files.legendUntracked')),
    h('span', { className: 'gg-legend-item' }, h('span', { className: 'gg-swatch gg-swatch-clean' }), t('files.legendClean')),
  )
}

function FilesView() {
  const tree = useStore((s) => s.tree)
  const treeError = useStore((s) => s.treeError)
  const cwd = useStore((s) => s.cwd)
  const [filter, setFilter] = React.useState('')
  const [collapsed, setCollapsed] = React.useState(() => new Set())

  React.useEffect(() => {
    registerTabLoader('files', async (w) => {
      const result = await getApi().tree(w)
      setState({ tree: result, treeError: null })
    })
    if (cwd !== null) {
      getApi().tree(cwd).then((r) => setState({ tree: r, treeError: null }))
        .catch((e) => setState({ tree: null, treeError: String(e?.message ?? e) }))
    }
  }, [cwd])

  const toggle = (path, isCollapsed) => {
    const next = new Set(collapsed)
    if (isCollapsed) next.delete(path)
    else next.add(path)
    setCollapsed(next)
  }

  const open = (file) => {
    const sel = {
      path: file.path,
      staged: false,
      untracked: file.state === 'untracked',
      cat: file.state === 'clean',
    }
    setState({ selected: sel, diff: { ...sel, loading: true, error: null, data: null }, tab: 'status' })
    refreshDiff()
  }

  if (treeError) return h('div', { className: 'gg-empty gg-empty-err' }, treeError)
  if (tree === null) return h('div', { className: 'gg-empty' }, t('status.loading'))
  const files = tree.files ?? []
  if (files.length === 0) return h('div', { className: 'gg-empty' }, t('files.empty'))

  const root = buildTree(files, filter)
  const rendered = { count: 0 }
  return h('div', { className: 'gg-files-view' },
    h('div', { className: 'gg-files-toolbar' },
      h('input', {
        className: 'gg-input',
        value: filter,
        placeholder: t('files.search'),
        onChange: (e) => setFilter(e.target.value),
      }),
      h(Legend, {})),
    h('div', { className: 'gg-files-tree' },
      h(Row, { node: root, depth: 0, collapsed, onToggle: toggle, onOpen: open, path: '', rendered })),
    tree.truncated && h('div', { className: 'gg-files-note' }, t('files.tooMany', { n: files.length })),
  )
}

module.exports = { FilesView }

},
"./v-footer.js": function (module, exports, require) {
/**
 * Sidebar footer entry: a Git button with a changed-files badge.
 * Registered into `sidebar.footer.action` (list / root scope).
 */
const { h, cx, ICONS, React } = require('./dom')
const { useStore, setState } = require('./store')
const { t } = require('./i18n')
const { applySession } = require('./control')

function changedCount(status) {
  if (!status || !status.files) return 0
  return status.files.length
}

function FooterButton(props) {
  const sessions = props.useSessions((s) => s)
  React.useEffect(() => {
    applySession(sessions)
  }, [sessions])
  const open = useStore((s) => s.open)
  const count = useStore((s) => changedCount(s.status))
  const statusError = useStore((s) => s.statusError)
  const check = useStore((s) => s.check)
  const wide = props.wide === true

  const title = t('panel.title')
  const onClick = () => setState({ open: !open })

  const badge = count > 0
    ? h('span', { className: 'gg-badge', title: `${count}` }, count > 99 ? '99+' : String(count))
    : null
  const dot = !badge && statusError && check?.repo === true
    ? h('span', { className: 'gg-badge gg-badge-err', title: statusError }, '!')
    : null

  return h('button', {
    type: 'button',
    className: cx('gg-footer-btn', open && 'gg-active'),
    title,
    onClick,
    'aria-label': title,
  },
    h('span', { className: 'gg-footer-icon' }, ICONS.git),
    wide && h('span', { className: 'gg-footer-label' }, 'Git'),
    (badge || dot) && h('span', { className: 'gg-footer-marks' }, badge, dot),
  )
}

module.exports = { FooterButton }

},
"./v-log.js": function (module, exports, require) {
/**
 * Commit log view with per-commit revert action.
 */
const { h, ICONS, React } = require('./dom')
const { useStore, setState } = require('./store')
const { t } = require('./i18n')
const { run, confirmThen, getApi, registerTabLoader } = require('./control')

function timeAgo(at) {
  if (!at) return ''
  const delta = Date.now() / 1000 - at
  if (delta < 60) return `${Math.max(1, Math.round(delta))}s`
  if (delta < 3600) return `${Math.round(delta / 60)}m`
  if (delta < 86400) return `${Math.round(delta / 3600)}h`
  if (delta < 86400 * 30) return `${Math.round(delta / 86400)}d`
  return new Date(at * 1000).toLocaleDateString()
}

function LogView() {
  const commits = useStore((s) => s.commits)
  const logError = useStore((s) => s.logError)
  const cwd = useStore((s) => s.cwd)
  const busy = useStore((s) => s.busy)

  React.useEffect(() => {
    registerTabLoader('log', async (w) => {
      const result = await getApi().log(w, 100, null)
      setState({ commits: result.commits, logError: null })
    })
    if (cwd !== null) {
      getApi().log(cwd, 100, null).then((r) => setState({ commits: r.commits, logError: null }))
        .catch((e) => setState({ commits: [], logError: String(e?.message ?? e) }))
    }
  }, [cwd])

  const revertCommit = (commit) => {
    confirmThen({
      body: t('confirm.revert', { commit: commit.hash.slice(0, 8) }),
      action: () => run(t('action.revert'), () => getApi().revert(cwd, commit.hash)),
    })
  }

  if (logError) return h('div', { className: 'gg-empty gg-empty-err' }, logError)
  if (commits.length === 0) return h('div', { className: 'gg-empty' }, t('commit.noCommits'))
  return h('div', { className: 'gg-log' },
    commits.map((c) => h('div', { className: 'gg-log-row', key: c.hash },
      h('div', { className: 'gg-log-main' },
        h('span', { className: 'gg-log-subject' }, c.subject),
        h('span', { className: 'gg-log-meta' },
          c.refs.map((r) => h('span', { className: 'gg-chip', key: r }, r)),
          h('span', { className: 'gg-log-hash' }, c.hash.slice(0, 8)),
          h('span', {}, c.author),
          h('span', { className: 'gg-log-time' }, timeAgo(c.time)),
        )),
      h('button', {
        type: 'button',
        className: 'gg-icon-btn gg-row-btn',
        disabled: busy,
        title: t('action.revert'),
        onClick: () => revertCommit(c),
      }, ICONS.undo),
    )))
}

module.exports = { LogView }

},
"./v-panel.js": function (module, exports, require) {
/**
 * The floating Git panel, registered into `shell.overlay` (list / root scope).
 */
const { h, cx, ICONS, React } = require('./dom')
const { useStore, setState, getState } = require('./store')
const { t } = require('./i18n')
const { applySession, refreshStatus, refreshRemotes, settleConfirm, run, getApi, refreshCheck } = require('./control')
const { StatusView } = require('./v-status')
const { FilesView } = require('./v-files')
const { LogView } = require('./v-log')
// ── Stage 2 功能(代码保留,暂不暴露给用户)────────────────────────────────────
// 分支 / 储藏 / AI 修改 三部分已实现且有测试,但尚未达到发布标准,先对用户隐藏。
// 启用方式:把对应条目加回下方 TABS(import 已保留,view 与 host 端点无需改动)。
const { BranchView } = require('./v-branch')       // 分支管理 (git/branches, git/switchBranch, git/merge, git/pull, git/push, git/fetch)
const { StashView } = require('./v-stash')         // 储藏 (git/stash)
const { TimelineView } = require('./v-timeline')   // AI 修改时间线 (git/activity)

// 当前发布(Stage 1)的标签页:
const TABS = [
  ['status', 'tab.status'],
  ['files', 'tab.files'],
  ['log', 'tab.log'],
  // Stage 2 启用时取消注释:
  // ['branches', 'tab.branches'],
  // ['stash', 'tab.stash'],
  // ['timeline', 'tab.timeline'],
]

function ConfirmModal() {
  const confirm = useStore((s) => s.confirm)
  if (confirm === null) return null
  const danger = confirm.danger === true
  return h('div', { className: 'gg-modal-backdrop', onClick: () => settleConfirm(false) },
    h('div', {
      className: cx('gg-modal', danger && 'gg-modal-danger'),
      onClick: (e) => e.stopPropagation(),
      role: 'dialog',
      'aria-modal': 'true',
    },
      h('div', { className: 'gg-modal-title' },
        h('span', { className: 'gg-modal-icon' }, ICONS.alert),
        t(danger ? 'confirm.dangerTitle' : 'confirm.title')),
      h('div', { className: 'gg-modal-body' }, confirm.body),
      h('div', { className: 'gg-modal-actions' },
        h('button', { type: 'button', className: 'gg-btn', onClick: () => settleConfirm(false) }, t('confirm.cancel')),
        h('button', {
          type: 'button',
          className: cx('gg-btn', danger ? 'gg-btn-danger' : 'gg-btn-primary'),
          autoFocus: true,
          onClick: () => settleConfirm(true),
        }, t('confirm.ok')),
      ),
    ),
  )
}

function Toast() {
  const toast = useStore((s) => s.toast)
  React.useEffect(() => {
    if (toast === null) return undefined
    const id = setTimeout(() => {
      if (getState().toast === toast) setState({ toast: null })
    }, 6000)
    return () => clearTimeout(id)
  }, [toast])
  if (toast === null) return null
  return h('div', { className: cx('gg-toast', toast.kind === 'error' ? 'gg-toast-err' : 'gg-toast-warn') },
    toast.text)
}

function OutputBox() {
  const output = useStore((s) => s.output)
  const [open, setOpen] = React.useState(false)
  if (output === null) return null
  return h('div', { className: 'gg-output' },
    h('button', { type: 'button', className: 'gg-output-head', onClick: () => setOpen(!open) },
      h('span', { className: 'gg-output-title' }, `${t('output.title')}: ${output.title}`),
      h('span', { className: 'gg-output-toggle' }, open ? ICONS.down : ICONS.up)),
    open && h('pre', { className: 'gg-output-body' }, output.text === '' ? t('output.empty') : output.text),
  )
}

function RemoteModal() {
  const openModal = useStore((s) => s.remoteModal)
  const cwd = useStore((s) => s.cwd)
  const busy = useStore((s) => s.busy)
  const [name, setName] = React.useState('origin')
  const [url, setUrl] = React.useState('')
  if (!openModal) return null
  const doAdd = async () => {
    const ok = await run(t('remote.add'), () => getApi().remoteAdd(cwd, name.trim() || 'origin', url.trim()))
    if (ok) {
      setState({ remoteModal: false })
      refreshRemotes(cwd)
    }
  }
  return h('div', { className: 'gg-modal-backdrop', onClick: () => setState({ remoteModal: false }) },
    h('div', { className: 'gg-modal', onClick: (e) => e.stopPropagation(), role: 'dialog', 'aria-modal': 'true' },
      h('div', { className: 'gg-modal-title' }, t('remote.addTitle')),
      h('label', { className: 'gg-field' },
        h('span', { className: 'gg-field-label' }, t('remote.name')),
        h('input', {
          className: 'gg-input', value: name,
          onChange: (e) => setName(e.target.value),
        })),
      h('label', { className: 'gg-field' },
        h('span', { className: 'gg-field-label' }, 'URL'),
        h('input', {
          className: 'gg-input', value: url, autoFocus: true,
          placeholder: t('remote.url.placeholder'),
          onChange: (e) => setUrl(e.target.value),
          onKeyDown: (e) => { if (e.key === 'Enter') doAdd() },
        })),
      h('div', { className: 'gg-modal-body' }, t('remote.sshNote')),
      h('div', { className: 'gg-modal-actions' },
        h('button', { type: 'button', className: 'gg-btn', onClick: () => setState({ remoteModal: false }) }, t('confirm.cancel')),
        h('button', {
          type: 'button',
          className: 'gg-btn gg-btn-primary',
          disabled: busy || url.trim() === '',
          onClick: doAdd,
        }, t('remote.add'))),
    ),
  )
}

function WorkspaceBar() {
  const check = useStore((s) => s.check)
  const status = useStore((s) => s.status)
  const busy = useStore((s) => s.busy)
  const busyLabel = useStore((s) => s.busyLabel)
  const cwd = useStore((s) => s.cwd)
  const remotes = useStore((s) => s.remotes)
  const branch = status?.branch
  const root = check?.root
  const name = typeof root === 'string' && root !== ''
    ? root.split(/[\\/]/).filter(Boolean).pop()
    : t('status.checking')

  const requireRemote = (action) => {
    if ((remotes ?? []).length === 0) {
      setState({ remoteModal: true, toast: { kind: 'warn', text: t('remote.emptyHint') } })
      return
    }
    action()
  }

  const doPull = () => requireRemote(() => run(t('action.pull'), () => getApi().pull(cwd, 'ff-only')))
  const doPush = () => requireRemote(() => run(t('action.push'), () => getApi().push(cwd)))
  const doFetch = () => requireRemote(() => run(t('action.fetch'), () => getApi().fetch(cwd)))

  return h('div', { className: 'gg-wsbar' },
    h('span', { className: 'gg-ws-name', title: root ?? undefined },
      h('span', { className: 'gg-ws-icon' }, ICONS.folder),
      name),
    branch?.head
      ? h('span', { className: 'gg-ws-branch' }, ICONS.branch, branch.head)
      : branch?.detached
        ? h('span', { className: 'gg-ws-branch gg-ws-detached' }, t('commit.detached'))
        : null,
    (branch?.ahead || branch?.behind)
      ? h('span', { className: 'gg-ws-ab' }, t('commit.aheadBehind', { a: branch.ahead ?? 0, b: branch.behind ?? 0 }))
      : null,
    h('span', { className: 'gg-ws-spacer' }),
    busy && h('span', { className: 'gg-ws-busy' }, busyLabel || t('commit.busy')),
    h('button', {
      type: 'button', className: 'gg-mini-btn', disabled: busy, title: 'git pull --ff-only',
      onClick: doPull,
    }, ICONS.down, 'Pull'),
    h('button', {
      type: 'button', className: 'gg-mini-btn', disabled: busy, title: 'git push',
      onClick: doPush,
    }, ICONS.up, 'Push'),
    h('button', {
      type: 'button', className: 'gg-mini-btn', disabled: busy, title: 'git fetch --all --prune',
      onClick: doFetch,
    }, ICONS.refresh, 'Fetch'),
    h('button', {
      type: 'button', className: cx('gg-icon-btn', (remotes ?? []).length === 0 && 'gg-icon-warn'),
      title: (remotes ?? []).length === 0 ? t('remote.emptyHint') : t('misc.remote'),
      onClick: () => setState({ remoteModal: true }),
    }, ICONS.globe),
    h('button', { type: 'button', className: 'gg-icon-btn', title: t('action.refresh'), onClick: () => refreshStatus() }, ICONS.refresh),
  )
}

function GitPanel(props) {
  const sessions = props.useSessions((s) => s)
  React.useEffect(() => {
    applySession(sessions)
  }, [sessions])
  const open = useStore((s) => s.open)
  const cwd = useStore((s) => s.cwd)
  const running = useStore((s) => s.sessionRunning)
  const check = useStore((s) => s.check)
  const busy = useStore((s) => s.busy)
  const [width, setWidth] = React.useState(460)
  const [tab, setTabLocal] = React.useState('status')
  const dragRef = React.useRef(null)

  React.useEffect(() => {
    setState({ tab })
  }, [tab])

  const onTab = (next) => {
    setTabLocal(next)
    setState({ tab: next })
  }

  const onDragStart = (e) => {
    e.preventDefault()
    const startX = e.clientX
    const startW = width
    dragRef.current = { startX, startW }
    const move = (ev) => {
      if (!dragRef.current) return
      const dx = startX - ev.clientX
      setWidth(Math.max(340, Math.min(800, startW + dx)))
    }
    const up = () => {
      dragRef.current = null
      window.removeEventListener('pointermove', move)
      window.removeEventListener('pointerup', up)
    }
    window.addEventListener('pointermove', move)
    window.addEventListener('pointerup', up)
  }

  if (!open) return null

  let body = null
  if (cwd === null) {
    body = h('div', { className: 'gg-empty' }, t('status.noSession'))
  } else if (check === null) {
    body = h('div', { className: 'gg-empty' }, t('status.checking'))
  } else if (check.repo === false) {
    body = h('div', { className: 'gg-empty' },
      check.nested > 0
        ? h('div', { className: 'gg-empty-title' }, `检测到 ${check.nested} 个嵌套 Git 仓库(位于工作区子目录),暂不支持多仓库,请将会话工作区指向其中一个仓库目录`)
        : h('div', { className: 'gg-empty-title' }, check.gitVersion === '' ? t('status.noGit') : t('status.notRepo')),
      check.nested > 0 ? null : h('button', {
        type: 'button',
        className: 'gg-btn gg-btn-primary',
        disabled: busy,
        onClick: () => initRepo(cwd),
      }, t('action.init')))
  } else {
    body = h('div', { className: 'gg-tabs' },
      h('div', { className: 'gg-tabbar', role: 'tablist' },
        TABS.map(([key, label]) => h('button', {
          type: 'button',
          role: 'tab',
          key,
          className: cx('gg-tab', tab === key && 'gg-tab-active'),
          onClick: () => onTab(key),
        }, t(label)))),
      h('div', { className: 'gg-tabbody' },
        tab === 'status' && h(StatusView, {}),
        tab === 'files' && h(FilesView, {}),
        tab === 'log' && h(LogView, {}),
        tab === 'branches' && h(BranchView, {}),
        tab === 'stash' && h(StashView, {}),
        tab === 'timeline' && h(TimelineView, {}),
      ),
    )
  }

  return h('div', { className: 'gg-panel', style: { width: `${width}px` } },
    h('div', { className: 'gg-resize', onPointerDown: onDragStart }),
    h('div', { className: 'gg-panel-head' },
      h('span', { className: 'gg-panel-title' }, t('panel.title')),
      h('button', { type: 'button', className: 'gg-icon-btn', title: t('panel.close'), onClick: () => setState({ open: false }) }, ICONS.close)),
    running && h('div', { className: 'gg-banner' }, ICONS.robot, t('timeline.running')),
    h(WorkspaceBar, {}),
    h(OutputBox, {}),
    h('div', { className: 'gg-panel-body' }, body),
    h(RemoteModal, {}),
    h(ConfirmModal, {}),
    h(Toast, {}),
  )
}

async function initRepo(cwd) {
  const ok = await run(t('action.init'), async () => getApi().init(cwd))
  if (ok) await refreshCheck()
}

module.exports = { GitPanel }

},
"./v-stash.js": function (module, exports, require) {
/**
 * Stash view: list, push, pop, apply, drop.
 */
const { h, React } = require('./dom')
const { useStore, setState } = require('./store')
const { t } = require('./i18n')
const { run, confirmThen, getApi, registerTabLoader } = require('./control')

function StashView() {
  const stashes = useStore((s) => s.stashes)
  const cwd = useStore((s) => s.cwd)
  const busy = useStore((s) => s.busy)
  const [msg, setMsg] = React.useState('')

  React.useEffect(() => {
    registerTabLoader('stash', async (w) => {
      const result = await getApi().stash(w, 'list', null, null)
      setState({ stashes: result.stashes })
    })
    if (cwd !== null) {
      getApi().stash(cwd, 'list', null, null).then((r) => setState({ stashes: r.stashes })).catch(() => {})
    }
  }, [cwd])

  const doPush = () => run(t('action.stashPush'), () => getApi().stash(cwd, 'push', msg.trim() || null, null))
  const doPop = (ref) => confirmThen({
    body: t('confirm.popStash', { ref }),
    action: () => run(t('action.pop'), () => getApi().stash(cwd, 'pop', null, ref)),
  })
  const doApply = (ref) => run(t('action.apply'), () => getApi().stash(cwd, 'apply', null, ref))
  const doDrop = (ref) => confirmThen({
    danger: true,
    body: t('confirm.dropStash', { ref }),
    action: () => run(t('action.drop'), () => getApi().stash(cwd, 'drop', null, ref)),
  })

  return h('div', { className: 'gg-stash' },
    h('div', { className: 'gg-stash-new' },
      h('input', {
        className: 'gg-input',
        value: msg,
        placeholder: t('stash.placeholder'),
        onChange: (e) => setMsg(e.target.value),
        onKeyDown: (e) => { if (e.key === 'Enter') doPush() },
      }),
      h('button', { type: 'button', className: 'gg-btn gg-btn-primary', disabled: busy, onClick: doPush }, t('action.stashPush'))),
    stashes.length === 0
      ? h('div', { className: 'gg-empty' }, t('stash.empty'))
      : h('div', { className: 'gg-stash-list' },
        h('div', { className: 'gg-group-name' }, t('stash.list')),
        stashes.map((s) => h('div', { className: 'gg-stash-row', key: s.ref },
          h('span', { className: 'gg-stash-ref' }, s.ref),
          h('span', { className: 'gg-stash-subject' }, s.subject),
          h('span', { className: 'gg-spacer' }),
          h('button', { type: 'button', className: 'gg-mini-btn', disabled: busy, onClick: () => doApply(s.ref) }, t('action.apply')),
          h('button', { type: 'button', className: 'gg-mini-btn', disabled: busy, onClick: () => doPop(s.ref) }, t('action.pop')),
          h('button', { type: 'button', className: 'gg-mini-btn gg-mini-danger', disabled: busy, onClick: () => doDrop(s.ref) }, t('action.drop')),
        ))))
}

module.exports = { StashView }

},
"./v-status.js": function (module, exports, require) {
/**
 * Status view: staged/unstaged/untracked/conflict groups, commit box, diff pane.
 */
const { h, cx, ICONS, React } = require('./dom')
const { useStore, setState, getState } = require('./store')
const { t } = require('./i18n')
const { run, confirmThen, getApi, refreshDiff } = require('./control')

const LETTER_CLASS = {
  M: 'gg-l-m', A: 'gg-l-a', D: 'gg-l-d', R: 'gg-l-r', C: 'gg-l-c', U: 'gg-l-u', '?': 'gg-l-q', T: 'gg-l-t',
}

function groupFiles(status) {
  const staged = []
  const unstaged = []
  const untracked = []
  const conflicts = []
  for (const f of status?.files ?? []) {
    const conflict = f.x === 'U' || f.y === 'U'
    if (conflict) conflicts.push(f)
    if (f.x === '?') untracked.push(f)
    else {
      if (f.x !== ' ' && f.x !== '.' && !conflict) staged.push(f)
      if (f.y !== ' ' && f.y !== '.' && f.x !== '?' && !conflict) unstaged.push(f)
    }
  }
  return { staged, unstaged, untracked, conflicts }
}

function FileRow({ file, kind, onOpen, onToggle, onDiscard }) {
  const display = kind === 'staged' ? file.x : kind === 'untracked' ? '?' : file.y
  const renamed = display === 'R' || file.origPath !== undefined
  const name = file.path.split('/').pop()
  const dir = file.path.includes('/') ? file.path.slice(0, file.path.length - name.length) : ''
  const sub = file.sub.startsWith('S') ? ' (submodule)' : ''

  return h('div', {
    className: cx('gg-file', kind === 'conflict' && 'gg-file-conflict'),
    onClick: () => onOpen(),
    title: file.path + sub,
  },
    h('button', {
      type: 'button',
      className: cx('gg-letter', LETTER_CLASS[display]),
      title: t('action.stage'),
      onClick: (e) => { e.stopPropagation(); onToggle() },
    }, display),
    h('span', { className: 'gg-file-main' },
      h('span', { className: 'gg-file-dir' }, dir),
      h('span', { className: 'gg-file-name' }, name + sub),
      renamed && h('span', { className: 'gg-file-renamed' }, `← ${file.origPath}`)),
    onDiscard && h('button', {
      type: 'button',
      className: 'gg-icon-btn gg-row-btn',
      title: t('action.discard'),
      onClick: (e) => { e.stopPropagation(); onDiscard() },
    }, ICONS.undo),
  )
}

function Group({ label, files, kind, onOpen, onToggle, onDiscard, extra }) {
  if (files.length === 0 && extra === undefined) return null
  return h('div', { className: 'gg-group' },
    h('div', { className: 'gg-group-head' },
      h('span', { className: 'gg-group-name' }, t(label)),
      h('span', { className: 'gg-group-count' }, files.length),
      extra),
    h('div', { className: 'gg-group-body' },
      files.map((f) => h(FileRow, {
        key: `${kind}:${f.path}`,
        file: f,
        kind,
        onOpen: () => onOpen(f, kind),
        onToggle: () => onToggle(f, kind),
        onDiscard: onDiscard ? () => onDiscard(f, kind) : undefined,
      }))))
}

function CommitBox() {
  const msg = useStore((s) => s.commitMsg)
  const identity = useStore((s) => s.identity)
  const status = useStore((s) => s.status)
  const busy = useStore((s) => s.busy)
  const cwd = useStore((s) => s.cwd)
  const groups = groupFiles(status)
  const stagedCount = groups.staged.length

  const [aiBusy, setAiBusy] = React.useState(false)

  const doCommit = async () => {
    if (msg.trim() === '') return
    const ok = await run(t('action.commit'), () => getApi().commit(cwd, msg.trim()))
    if (ok) setState({ commitMsg: '' })
  }
  const onKeyDown = (e) => {
    if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) {
      e.preventDefault()
      doCommit()
    }
  }
  const stageAll = async () => {
    const paths = [...groups.unstaged, ...groups.untracked].map((f) => f.path)
    if (paths.length === 0) return
    await run(t('action.stageAll'), () => getApi().stage(cwd, paths))
  }

  const aiGenerate = async () => {
    if (busy || aiBusy) return
    setAiBusy(true)
    try {
      const result = await getApi().generateCommitMessage(cwd)
      if (result && result.ok && result.message) {
        setState({ commitMsg: result.message })
      }
    } catch (error) {
      setState({ toast: { kind: 'error', text: String(error?.message ?? error) } })
    } finally {
      setAiBusy(false)
    }
  }

  return h('div', { className: 'gg-commit' },
    h('textarea', {
      className: 'gg-commit-input',
      value: msg,
      placeholder: t('commit.placeholder'),
      rows: 3,
      onChange: (e) => setState({ commitMsg: e.target.value }),
      onKeyDown,
    }),
    h('div', { className: 'gg-commit-foot' },
      identity
        ? h('span', { className: 'gg-identity', title: t('commit.identity') },
          `${t('commit.identity')} ${identity.name ?? '?'} <${identity.email ?? '?'}>`)
        : h('span', { className: 'gg-identity gg-identity-missing' }, t('commit.identityMissing')),
      h('span', { className: 'gg-spacer' }),
      h('button', {
        type: 'button',
        className: 'gg-mini-btn',
        disabled: busy || aiBusy || stagedCount === 0,
        title: t('action.aiCommitTooltip'),
        onClick: aiGenerate,
      }, aiBusy ? '…' : t('action.aiCommit')),
      h('button', { type: 'button', className: 'gg-btn', disabled: busy || aiBusy, onClick: stageAll }, t('action.stageAll')),
      h('button', {
        type: 'button',
        className: 'gg-btn gg-btn-primary',
        disabled: busy || stagedCount === 0 || msg.trim() === '',
        onClick: doCommit,
        title: stagedCount === 0 ? t('commit.hint') : undefined,
      }, `${t('action.commit')}${stagedCount > 0 ? ` (${stagedCount})` : ''}`),
    ),
  )
}

function DiffPane() {
  const selected = useStore((s) => s.selected)
  const diff = useStore((s) => s.diff)
  if (selected === null) {
    return h('div', { className: 'gg-diff' }, h('div', { className: 'gg-empty' }, t('diff.empty')))
  }
  if (diff === null || diff.loading) {
    return h('div', { className: 'gg-diff' }, h('div', { className: 'gg-empty' }, t('status.loading')))
  }
  if (diff.error !== null) {
    return h('div', { className: 'gg-diff' }, h('div', { className: 'gg-empty gg-empty-err' }, diff.error))
  }
  // file-content mode (clean files opened from the tree view)
  if (selected.cat === true) {
    const data = diff.data ?? {}
    const lines = (data.content ?? '').split('\n')
    const hasTrailing = lines.length > 1 && lines[lines.length - 1] === ''
    if (hasTrailing) lines.pop()
    return h('div', { className: 'gg-diff' },
      h('div', { className: 'gg-diff-head' },
        h('span', { className: 'gg-diff-path' }, selected.path),
        h('span', { className: 'gg-chip' }, t('cat.title'))),
      h('div', { className: 'gg-diff-scroll' },
        data.binary
          ? h('div', { className: 'gg-empty' }, t('diff.binary'))
          : data.tooLarge
            ? h('div', { className: 'gg-empty' }, t('diff.tooLarge', { size: data.size }))
            : h('div', { className: 'gg-hunks' },
              lines.map((text, i) => h('div', { className: 'gg-line gg-line-ctx', key: i },
                h('span', { className: 'gg-line-no' }, ''),
                h('span', { className: 'gg-line-no' }, i + 1),
                h('span', { className: 'gg-line-mark' }, ' '),
                h('span', { className: 'gg-line-text' }, text || ' '))))),
    )
  }
  const file = diff.data?.diff?.files?.[0]
  if (!file) {
    return h('div', { className: 'gg-diff' }, h('div', { className: 'gg-empty' }, t('diff.empty')))
  }
  return h('div', { className: 'gg-diff' },
    h('div', { className: 'gg-diff-head' },
      h('span', { className: 'gg-diff-path' }, file.newPath),
      selected.staged && h('span', { className: 'gg-chip' }, t('group.staged')),
      selected.untracked && h('span', { className: 'gg-chip' }, t('diff.newFile')),
      (file.oldPath && file.oldPath !== file.newPath) && h('span', { className: 'gg-diff-rename' }, `${file.oldPath} → ${file.newPath}`),
    ),
    h('div', { className: 'gg-diff-scroll' },
      file.binary
        ? h('div', { className: 'gg-empty' }, t('diff.binary'))
        : file.tooLarge
          ? h('div', { className: 'gg-empty' }, t('diff.tooLarge', { size: file.size }))
          : file.hunks.length === 0
            ? h('div', { className: 'gg-empty' }, t('group.clean'))
            : h('div', { className: 'gg-hunks' },
              file.hunks.map((hunk, i) => h('div', { className: 'gg-hunk', key: i },
                h('div', { className: 'gg-hunk-head' }, `@@ -${hunk.oldStart},${hunk.oldCount} +${hunk.newStart},${hunk.newCount} @@`),
                hunk.lines.map((line, j) => h('div', {
                  className: cx('gg-line', line.type === 'add' ? 'gg-line-add' : line.type === 'del' ? 'gg-line-del' : 'gg-line-ctx'),
                  key: j,
                },
                  h('span', { className: 'gg-line-no' }, line.oldLine ?? ''),
                  h('span', { className: 'gg-line-no' }, line.newLine ?? ''),
                  h('span', { className: 'gg-line-mark' }, line.type === 'add' ? '+' : line.type === 'del' ? '-' : ' '),
                  h('span', { className: 'gg-line-text' }, line.text || ' '),
                  line.newline === false && h('span', { className: 'gg-line-nonl' }, '⏎'),
                ))))),
    ),
  )
}

function StatusView() {
  const status = useStore((s) => s.status)
  const statusError = useStore((s) => s.statusError)
  const cwd = useStore((s) => s.cwd)
  const busy = useStore((s) => s.busy)
  const groups = groupFiles(status)

  React.useEffect(() => {
    // load identity once per workspace
    if (cwd !== null) {
      getApi().identity(cwd).then((r) => setState({ identity: r })).catch(() => {})
    }
  }, [cwd])

  const openDiff = (file, kind) => {
    const sel = { path: file.path, staged: kind === 'staged', untracked: kind === 'untracked', cat: false }
    setState({ selected: sel, diff: { ...sel, loading: true, error: null, data: null } })
    refreshDiff()
  }

  const toggle = (file, kind) => {
    const fn = kind === 'staged'
      ? () => getApi().unstage(cwd, [file.path])
      : () => getApi().stage(cwd, [file.path])
    run(kind === 'staged' ? t('action.unstage') : t('action.stage'), fn).then(() => {
      const sel = getState().selected
      if (sel && sel.path === file.path) refreshDiff()
    })
  }

  const discard = (file, kind) => {
    confirmThen({
      danger: true,
      body: kind === 'untracked'
        ? t('confirm.cleanFile', { name: file.path })
        : t('confirm.discardFile', { name: file.path }),
      action: () => run(t('action.discard'), () => getApi().discard(cwd, [file.path], kind === 'untracked')).then(() => {
        const sel = getState().selected
        if (sel && sel.path === file.path) setState({ selected: null, diff: null })
      }),
    })
  }

  const unstageAll = () => {
    const paths = groups.staged.map((f) => f.path)
    if (paths.length === 0) return
    run(t('action.unstageAll'), () => getApi().unstage(cwd, paths))
  }

  const total = (status?.files ?? []).length
  return h('div', { className: 'gg-status' },
    h(CommitBox, {}),
    statusError
      ? h('div', { className: 'gg-empty gg-empty-err' }, `${t('status.error')}: ${statusError}`)
      : total === 0
        ? h('div', { className: 'gg-empty' }, t('group.clean'))
        : h('div', { className: 'gg-status-main' },
          h('div', { className: 'gg-files' },
            h(Group, {
              label: 'group.conflicts', files: groups.conflicts, kind: 'conflict',
              onOpen: openDiff, onToggle: (f) => { openDiff(f, 'conflict') },
            }),
            h(Group, {
              label: 'group.staged', files: groups.staged, kind: 'staged',
              onOpen: openDiff, onToggle: toggle,
              extra: groups.staged.length > 0 && h('button', { type: 'button', className: 'gg-mini-btn', disabled: busy, onClick: unstageAll }, t('action.unstageAll')),
            }),
            h(Group, {
              label: 'group.changes', files: groups.unstaged, kind: 'unstaged',
              onOpen: openDiff, onToggle: toggle, onDiscard: discard,
            }),
            h(Group, {
              label: 'group.untracked', files: groups.untracked, kind: 'untracked',
              onOpen: openDiff, onToggle: toggle, onDiscard: discard,
            })),
          h(DiffPane, {}),
        ),
  )
}

module.exports = { StatusView }

},
"./v-timeline.js": function (module, exports, require) {
/**
 * AI edit timeline: mutations attributed to (session, turn, tool, path).
 * Clicking a row opens the current diff of that path.
 */
const { h, React } = require('./dom')
const { useStore, setState, getState } = require('./store')
const { t } = require('./i18n')
const { getApi, registerTabLoader, refreshDiff } = require('./control')

function TimelineView() {
  const activity = useStore((s) => s.activity)
  const cwd = useStore((s) => s.cwd)

  React.useEffect(() => {
    registerTabLoader('timeline', async (w) => {
      const result = await getApi().activity(w, 100)
      setState({ activity: result.entries })
    })
    if (cwd !== null) {
      getApi().activity(cwd, 100).then((r) => setState({ activity: r.entries })).catch(() => {})
    }
  }, [cwd])

  const openPath = (entry) => {
    // make the path relative to the effective repo root (nested repos are
    // supported: check.root may be deeper than the session cwd)
    let path = entry.path
    const root = getState().check?.root
    if (root && path.toLowerCase().startsWith(root.toLowerCase())) {
      path = path.slice(root.length).replace(/^[\\/]+/, '')
    }
    // untracked files have no worktree diff: open the untracked content preview
    const status = getState().status
    const statusFile = status?.files?.find((f) => f.path === path)
    const untracked = statusFile !== undefined && statusFile.x === '?'
    const sel = { path, staged: false, untracked, cat: false }
    setState({ selected: sel, diff: { ...sel, loading: true, error: null, data: null }, tab: 'status' })
    refreshDiff()
  }

  if (activity.length === 0) {
    return h('div', { className: 'gg-empty' }, t('timeline.empty'))
  }
  return h('div', { className: 'gg-timeline' },
    h('div', { className: 'gg-group-name' }, t('timeline.title')),
    activity.map((e, i) => h('button', {
      type: 'button',
      className: 'gg-tl-row',
      key: i,
      onClick: () => openPath(e),
      title: e.path,
    },
      h('span', { className: 'gg-tl-tool' }, e.tool),
      h('span', { className: 'gg-tl-path' }, e.path),
      h('span', { className: 'gg-spacer' }),
      h('span', { className: 'gg-tl-meta' },
        t('timeline.turn', { turn: e.turn }),
        ' · ',
        e.sessionId.slice(0, 8),
        ' · ',
        new Date(e.at).toLocaleTimeString())),
    ))
}

module.exports = { TimelineView }

},
"./pkg-id.js": function (module, exports, require) {
module.exports = "@amorligno/dsh-git-gui"

}
    };
    var __cache = {};
    function __normalize(base, spec) {
      if (!spec.startsWith('.')) return null;
      var parts = base.split('/');
      parts.pop();
      for (var i = 0; i < spec.length; ) {
        if (spec.startsWith('./', i)) { i += 2; continue; }
        if (spec.startsWith('../', i)) { i += 3; parts.pop(); continue; }
        break;
      }
      var rest = spec.slice(i).split('/').filter(Boolean).join('/');
      var joined = parts.filter(function (p) { return p !== '' && p !== '.'; }).join('/');
      var id = './' + (joined === '' ? '' : joined + '/') + rest;
      if (!/.js$/.test(id)) id += '.js';
      return id;
    }
    function __load(id, base) {
      var resolved = __normalize(base, id);
      if (resolved === null) return require(id);
      if (Object.prototype.hasOwnProperty.call(__cache, resolved)) return __cache[resolved].exports;
      var mod = { exports: {} };
      __cache[resolved] = mod;
      var factory = __modules[resolved];
      if (factory === undefined) throw new Error("@amorligno/dsh-git-gui" + ': unknown module ' + resolved);
      factory(mod, mod.exports, function (spec) { return __load(spec, resolved); });
      return mod.exports;
    }
    return __load('./index.js', './entry.js');
  }
});
