/**
 * Micro-bundler for the dsh-git-gui client half (zero dependencies).
 *
 * DSH's browser module system loads exactly one classic script per plugin
 * (`/plugins/<id>/client.js`) that must call
 * `window.__ModuleLoader__.load({ id, factory })` with a CommonJS factory.
 * The module id MUST equal the npm package name (it is read from
 * package.json), and a synthetic `./pkg-id.js` module exposes that name to
 * client code. Relative requires resolve inside our own registry; bare
 * specifiers (`react`, `react/jsx-runtime`, `@deepseek-ai/...`) are handed
 * to the runtime `require` provided by the module table.
 *
 * Usage: node scripts/build-client.mjs [--watch]
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const SRC = path.join(ROOT, 'client-src')
const OUT = path.join(ROOT, 'lib', 'client.js')
const ID = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8')).name

function collectModules(dir, prefix = '.') {
  const modules = new Map()
  for (const entry of fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      for (const [id, source] of collectModules(full, `${prefix}/${entry.name}`)) modules.set(id, source)
    } else if (entry.isFile() && entry.name.endsWith('.js')) {
      modules.set(`${prefix}/${entry.name}`, fs.readFileSync(full, 'utf8'))
    }
  }
  return modules
}

function build() {
  const modules = collectModules(SRC)
  // synthetic module: the npm package name, available to client code
  modules.set('./pkg-id.js', `module.exports = ${JSON.stringify(ID)}\n`)
  const body = []
  for (const [id, source] of modules) {
    body.push(`${JSON.stringify(id)}: function (module, exports, require) {\n${source}\n}`)
  }
  const registry = body.join(',\n')

  const output = `/* generated by scripts/build-client.mjs — do not edit */\n`
    + `window.__ModuleLoader__.load({\n`
    + `  id: ${JSON.stringify(ID)},\n`
    + `  factory: function (require) {\n`
    + `    var __modules = {\n${registry}\n    };\n`
    + `    var __cache = {};\n`
    + `    function __normalize(base, spec) {\n`
    + `      if (!spec.startsWith('.')) return null;\n`
    + `      var parts = base.split('/');\n`
    + `      parts.pop();\n`
    + `      for (var i = 0; i < spec.length; ) {\n`
    + `        if (spec.startsWith('./', i)) { i += 2; continue; }\n`
    + `        if (spec.startsWith('../', i)) { i += 3; parts.pop(); continue; }\n`
    + `        break;\n`
    + `      }\n`
    + `      var rest = spec.slice(i).split('/').filter(Boolean).join('/');\n`
    + `      var joined = parts.filter(function (p) { return p !== '' && p !== '.'; }).join('/');\n`
    + `      var id = './' + (joined === '' ? '' : joined + '/') + rest;\n`
    + `      if (!/\.js$/.test(id)) id += '.js';\n`
    + `      return id;\n`
    + `    }\n`
    + `    function __load(id, base) {\n`
    + `      var resolved = __normalize(base, id);\n`
    + `      if (resolved === null) return require(id);\n`
    + `      if (Object.prototype.hasOwnProperty.call(__cache, resolved)) return __cache[resolved].exports;\n`
    + `      var mod = { exports: {} };\n`
    + `      __cache[resolved] = mod;\n`
    + `      var factory = __modules[resolved];\n`
    + `      if (factory === undefined) throw new Error(${JSON.stringify(ID)} + ': unknown module ' + resolved);\n`
    + `      factory(mod, mod.exports, function (spec) { return __load(spec, resolved); });\n`
    + `      return mod.exports;\n`
    + `    }\n`
    + `    return __load('./index.js', './entry.js');\n`
    + `  }\n`
    + `});\n`

  fs.mkdirSync(path.dirname(OUT), { recursive: true })
  fs.writeFileSync(OUT, output)
  const kb = Math.round(output.length / 1024)
  console.log(`built ${OUT} (${modules.size} modules, ${kb} KiB)`)
  return modules.size
}

const watch = process.argv.includes('--watch')
const count = build()
if (watch) {
  let timer = null
  const rebuild = () => {
    if (timer !== null) return
    timer = setTimeout(() => {
      timer = null
      try {
        build()
      } catch (error) {
        console.error('build failed:', error)
      }
    }, 120)
  }
  fs.watch(SRC, { recursive: true }, rebuild)
  console.log(`watching ${SRC} — rebuilds update lib/client.js (client HMR picks it up while the dsh web watcher runs)`)
} else if (count === 0) {
  console.error('no client modules found')
  process.exitCode = 1
}
